# Configuration for homarr setup

# Name of the big-bear-homarr application
# Service definitions for the big-bear-homarr application
services:
  homarr:
    # Name of the container
    container_name: homarr
    # Image to be used for the container
    image: ghcr.io/ajnart/homarr:0.16.0
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local homarr/configs directory to /app/data/configs inside the container
      - ${APP_DATA_DIR}/configs:/app/data/configs
      # Mounting the local homarr/icons directory to /app/public/icons inside the container
      - ${APP_DATA_DIR}/icons:/app/public/icons
      # Mounting the local homarr/dat directory to /data inside the container
      - ${APP_DATA_DIR}/data:/data
      # Mounting docker.sock to allow docker management via Homarr
      - /var/run/docker.sock:/var/run/docker.sock
    # Ports mapping between host and container
    ports:
      # Mapping port 7575 of the host to port 7575 of the container
      - "${APP_PORT}:7575"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
