# Configuration for big-bear-portainer-agent setup
# Service definitions for the big-bear-portainer-agent application
services:
  portainer-agent:
    container_name: portainer-agent # Name of the running container
    image: portainer/agent:2.36.0 # Image to be used
    network_mode: bridge # Network mode to be used
    ports: # Port mapping between host and container
      - ${APP_PORT}:9001
      # Maps port 9001 on the host to port 9001 in the container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Bind mount for Docker socket
      - /var/lib/docker/volumes:/var/lib/docker/volumes # Bind mount for Docker volumes
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
