# Configuration for nexterm setup

# Name of the big-bear-nexterm application
# Service definitions for the big-bear-nexterm application
services:
  nexterm:
    # Name of the container
    container_name: nexterm
    # Image to be used for the container
    image: germannewsmaker/nexterm:1.0.7-OPEN-PREVIEW
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local nexterm_data directory to /app/data inside the container
      - ${APP_DATA_DIR}/data:/app/data
    # Ports mapping between host and container
    ports:
      # Mapping port 6989 of the host to port 6989 of the container
      - "${APP_PORT}:6989"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
