# Configuration for retroarch-web setup

# Name of the big-bear-retroarch-web application
# Service definitions for the big-bear-retroarch-web application
services:
  retroarch-web:
    # Name of the container
    container_name: retroarch-web
    # Image to be used for the container
    image: inglebard/retroarch-web:latest
    # Container restart policy
    restart: unless-stopped
    # Environment variables
    environment:
      - ROOT_WWW_PATH="/var/www/html"
    # Ports mapping between host and container
    ports:
      # Mapping port 8080 of the host to port 80 of the container
      - "${APP_PORT}:80"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
