services:
  jlesage-handbrake:
    container_name: jlesage-handbrake # Name of the Docker container
    image: jlesage/handbrake:v26.01.1 # Docker image for the Handbrake
    ports:
      - "${APP_PORT}:5800" # Expose port 5800 for VNC access
    environment:
      - VNC_PASSWORD=casaos # Set the VNC password to 'casaos'
    volumes:
      - ${APP_DATA_DIR}/config:/config:rw
      - ${APP_DATA_DIR}/storage:/storage:ro
      - ${APP_DATA_DIR}/watch:/watch:rw
      - ${APP_DATA_DIR}/output:/output:rw
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
