services:
  chromium:
    container_name: chromium # Name of the Docker container
    image: linuxserver/chromium:version-6ae43f81 # Docker image for the chromium browser
    ports:
      - "${APP_PORT}:3000" # Expose port 3000 for HTTP VNC access
      - "3001:3001" # Expose port 3001 for HTTPS VNC access
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CHROME_CLI=https://community.bigbeartechworld.com/ # Set the default URL to Big Bear Tech World
    shm_size: 1gb # Allocate 1 GB of shared memory
    volumes:
      - ${APP_DATA_DIR}/config:/config # Mount the config directory for persistent data
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
