# Configuration for big-bear-mailpit setup
# Service definitions for the big-bear-mailpit application
services:
  mailpit:
    image: axllent/mailpit:v1.27 # Image for the app service
    container_name: mailpit # Container name for the app service
    restart: unless-stopped # Restart policy for the container
    volumes: # Volumes to mount for the app service
      - ${APP_DATA_DIR}/data:/data
    environment: # Environment variables for the app service
      - TZ=UTC
    ports: # Ports to expose for the app service
      - "${APP_PORT}:8025"
      - "1025:1025"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
