# Configuration for ollama-amd setup

# Name of the big-bear-ollama-amd application
# Service definitions for the big-bear-ollama-amd application
services:
  ollama-amd:
    # Name of the container
    container_name: ollama-amd
    # Image to be used for the container
    image: ollama/ollama:0.13.0-rocm
    # Container restart policy
    restart: unless-stopped
    # Environment variables
    environment:
      - PORT=11434
    # Volumes to be mounted to the container
    volumes:
      - ${APP_DATA_DIR}/.ollama:/root/.ollama
    # Ports mapping between host and container
    ports:
      # Mapping port 11434 of the host to port 11434 of the container
      - "${APP_PORT}:11434"
    devices:
      # Attach GPU
      - /dev/kfd
      - /dev/dri
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
