services:
  dashdot:
    image: mauricenino/dashdot:6.2.4
    ports:
      - "${APP_PORT}:3001"
    volumes:
      - ${APP_DATA_DIR}/data:/mnt/host
    privileged: true
    container_name: dashdot
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
