# Configuration for filebrowser-quantum setup

# Name of the big-bear-filebrowser-quantum application
# Service definitions for the big-bear-filebrowser-quantum application
services:
  filebrowser-quantum:
    # Name of the container
    container_name: filebrowser-quantum
    # Image to be used for the container
    image: gtstef/filebrowser:1.1.2-stable
    # Container restart policy
    restart: unless-stopped
    # Environment variables
    environment:
      - TZ=UTC
    # Volumes to be mounted to the container
    volumes:
      - ${APP_DATA_DIR}/data:/home/filebrowser/data # Database and config
      - ${APP_DATA_DIR}/srv:/srv # Served files
    # Ports mapping between host and container
    ports:
      - "${APP_PORT}:80"
    # Networks for the big-bear-filebrowser-quantum application
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: "true"
networks:
  tipi_main_network:
    external: true
