# Configuration for goaway setup

# Application Name
# Services used in the application
services:
  goaway:
    # Name of the container
    container_name: goaway
    # Docker image to be used
    image: pommee/goaway:0.62.19
    # Restart policy for the service
    restart: unless-stopped
    # Port mappings for the service
    ports:
      - "${APP_PORT}:53/udp" # DNS port UDP
      - "53:53/tcp" # DNS port TCP
      - "8080:8080" # Web dashboard port
    # Network mode for the service
    network_mode: bridge
    # Volumes for the service HOST -> CONTAINER
    volumes:
      - ${APP_DATA_DIR}/config:/app/config
    # Capabilities required for DNS services
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
