# Configuration for mealie setup

# Name of the big-bear-mealie application
# Service definitions for the big-bear-mealie application
services:
  mealie:
    # Name of the container
    container_name: mealie
    # Image to be used for the container
    image: hkotel/mealie:v3.11.0
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local mealie_data directory to /app/data inside the container
      - ${APP_DATA_DIR}/data:/app/data
    # Ports mapping between host and container
    ports:
      # Mapping port 7575 of the host to port 9000 of the container
      - "${APP_PORT}:9000"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
