# Configuration for vert setup

# Name of the big-bear-vert application
# Service definitions for the big-bear-vert application
services:
  vert:
    # Name of the container
    container_name: vert
    # Image to be used for the container
    image: ghcr.io/vert-sh/vert:sha-a1b0b15
    # Container restart policy
    restart: unless-stopped
    # Ports mapping between host and container
    ports:
      # Mapping port 3030 of the host to port 80 of the container
      - "${APP_PORT}:80"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
