# Configuration for big-bear-actual-server setup
name: big-bear-actual-server
# Service definitions for the big-bear-actual-server application
services:
  actual-server:
    image: actualbudget/actual-server:25.11.0 # The Docker image to use (latest version of actual-server)
    container_name: actual-server # Name of the container instance
    volumes:
      - ${APP_DATA_DIR}/data:/data # Mounting the data volume
    ports:
      - "${APP_PORT}:5006" # Expose actual-server's port 5006 on the host's port 5006
    restart: unless-stopped # Policy to restart the container if it stops unexpectedly
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
