# Configuration for audiobookshelf setup

# Name of the big-bear-audiobookshelf application
# Service definitions for the big-bear-audiobookshelf application
services:
  audiobookshelf:
    # Name of the container
    container_name: audiobookshelf
    # Image to be used for the container
    image: ghcr.io/advplyr/audiobookshelf:2.30.0
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      - ${APP_DATA_DIR}/media/data/books/spoken:/audiobooks
      - ${APP_DATA_DIR}/media/data/podcasts:/podcasts
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/metadata:/metadata
    # Ports mapping between host and container
    ports:
      # Mapping port 8080 of the host to port 80 of the container
      - "${APP_PORT}:80"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
