# Configuration for ComposeToolbox setup

# Name of the big-bear-composetoolbox application
# Service definitions for the big-bear-composetoolbox application
services:
  composetoolbox:
    # Environment variables
    environment:
      # Node environment
      NODE_ENV: production
    # Image to be used for the container
    image: ghcr.io/bluegoosemedia/composetoolbox:latest
    pull_policy: always
    # Ports mapping between host and container
    ports:
      - "${APP_PORT}:3000"
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    # Name of the container
    container_name: "composetoolbox"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
