# Configuration for kavita setup

# Name of the big-bear-kavita application
# Service definitions for the big-bear-kavita application
services:
  kavita:
    # Name of the container
    container_name: kavita
    # Image to be used for the container
    image: jvmilazz0/kavita:0.8.9
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      - ${APP_DATA_DIR}/data/kavita-config:/kavita/config
      - ${APP_DATA_DIR}/media/data/books:/books
      - ${APP_DATA_DIR}/media/data/comics:/comics
      - ${APP_DATA_DIR}/media/data/manga:/manga
    # Ports mapping between host and container
    ports:
      # Mapping port 5000 of the host to port 5000 of the container
      - "${APP_PORT}:5000"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
