# Configuration for erugo setup

# Name of the big-bear-erugo application
# Service definitions for the big-bear-erugo application
services:
  erugo:
    # Name of the container
    container_name: erugo
    # Image to be used for the container
    image: wardy784/erugo:0.2.2
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting storage directory to allow erugo to save data
      - ${APP_DATA_DIR}/storage:/var/www/html/storage
    # Ports mapping between host and container
    ports:
      # Mapping port 9997 of the host to port 80 of the container
      - "${APP_PORT}:80"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
