# Configuration for Portracker setup

# Name of the big-bear-portracker application
# Service definitions for the big-bear-portracker application
services:
  portracker:
    # Name of the container
    container_name: portracker
    # Image to be used for the container
    image: mostafawahied/portracker:1.1
    # Container restart policy
    restart: unless-stopped
    # Environment variables for service configuration
    environment:
      - PORT=4999
      - DATABASE_PATH=/data/portracker.db
      - TRUSTED_LOCAL_EMAIL=your@email.com
      - CACHE_TIMEOUT_MS=30000
      - DISABLE_CACHE=false
      - INCLUDE_UDP=false
      - DEBUG=false
    # Volumes to be mounted to the container
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    # Ports mapping between host and container
    ports:
      # Mapping port 4999 of the host to port 4999 of the container
      - "${APP_PORT}:4999"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
