# Configuration for chatpad setup

# Name of the big-bear-chatpad application
# Service definitions for the big-bear-chatpad application
services:
  chatpad:
    # Name of the container
    container_name: chatpad
    # Image to be used for the container
    image: ghcr.io/deiucanta/chatpad:f45cd53bc410412610c1ba1cbd84cd137d8e167d
    # Container restart policy
    restart: unless-stopped
    # Ports mapping between host and container
    ports:
      # Mapping port 8080 of the host to port 80 of the container
      - "${APP_PORT}:80"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
